apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  type: LoadBalancer
  selector:
    app: base-service
  ports:
    - name: base-service
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000