apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  type: NodePort
  selector:
    app: base-service
  ports:
    - name: base-service
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000