name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build Docker image
        run: docker build -t crm-base-service .
#      - name: Deploy to Kubernetes
#        env:
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#        run: |
#          export POSTGRES_PASSWORD
#          kubectl apply -f k8s/app-deployment.yaml

      - run: echo "🍏 This job's status is ${{ job.status }}."